language: generic

script:
  - swift build && swift test

matrix:
  allow_failures:
    - os: linux
  include:
    - os: linux
      dist: trusty
      sudo: required
      before_script:
          - sudo apt-get update
          - sudo apt-get install -y build-essential git libcurl3 libblocksruntime-dev clang libicu-dev uuid-dev
          - wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
          - gpg --keyserver hkp://pool.sks-keyservers.net --refresh-keys Swift
          - wget https://swift.org/builds/swift-4.2-convergence/ubuntu1404/swift-4.2-CONVERGENCE/swift-4.2-CONVERGENCE-ubuntu14.04.tar.gz
          - gunzip swift-4.2-CONVERGENCE-ubuntu14.04.tar.gz
          - tar -xvf swift-4.2-CONVERGENCE-ubuntu14.04.tar
          - export PATH=${PWD}/swift-4.2-CONVERGENCE-ubuntu14.04/usr/bin:"${PATH}"
    - os: osx
      language: objective-c
      osx_image: xcode9.2
      before_script:
        - brew install couchdb
        - brew services start couchdb

services:
    - couchdb
